function plotParticleDataHistory3D( timeVector, particleData, index, dataName, outputMATLAB, fileName, ...
    xAxisLabel, yAxisLabel, colorMap, nParticles )

    plotParticleDataHistory( timeVector, particleData, ...
        index, [dataName, ' - X Direction'], outputMATLAB, ['X_', fileName], ...
        xAxisLabel, ['X ', yAxisLabel], colorMap, ...
        nParticles, 1 );

    plotParticleDataHistory( timeVector, particleData, ...
        index, [dataName, ' - Y Direction'], outputMATLAB, ['Y_', fileName], ...
        xAxisLabel, ['Y ', yAxisLabel], colorMap, ...
        nParticles, 2 );

    plotParticleDataHistory( timeVector, particleData, ...
        index, [dataName, ' - Z Direction'], outputMATLAB, ['Z_', fileName], ...
        xAxisLabel, ['Z ', yAxisLabel], colorMap, ...
        nParticles, 3 );

end

