function plotParticleDataHistory3D( timeVector, particleData, index, dataName, outputMATLAB, fileName, ...
    extension, xAxisLabel, yAxisLabel, colorMap, nParticles )

    plotParticleDataHistory( timeVector, particleData, ...
        index, [dataName, ' - X Direction'], outputMATLAB, [fileName, '_X'], ...
        extension, xAxisLabel, ['X ', yAxisLabel], colorMap, ...
        nParticles, 1 );

    plotParticleDataHistory( timeVector, particleData, ...
        index, [dataName, ' - Y Direction'], outputMATLAB, [fileName, '_Y'], ...
        extension, xAxisLabel, ['Y ', yAxisLabel], colorMap, ...
        nParticles, 2 );

    plotParticleDataHistory( timeVector, particleData, ...
        index, [dataName, ' - Z Direction'], outputMATLAB, [fileName, '_Z'], ...
        extension, xAxisLabel, ['Z ', yAxisLabel], colorMap, ...
        nParticles, 3 );

end

